auto: true
destination: instituteforparafunctionalexploration.com
url: http://instituteforparafunctionalexploration.com
markdown: kramdown
highlighter: true

permalink: /:categories/:title

--- # Categories
- about
- projects
- page

gems:
- jemoji
- jekyll-sitemap

sitemap:
	file: "/sitemap.xml"
	exclude:
		- "/im.html"
	include_posts:
		- "/index.html"
	change_frequency_name: "change_frequency"
	priority_name: "priority"